"""
Mapeo de nombres de equipos FBref → codigo_fifa (48 selecciones clasificadas
al Mundial 2026).

Compartido entre los pipelines fbref_squads y fbref_fixtures.
"""

FBREF_NAME_TO_FIFA: dict[str, str] = {
    "Algeria":              "ALG",
    "Argentina":            "ARG",
    "Australia":            "AUS",
    "Austria":              "AUT",
    "Belgium":              "BEL",
    "Bosnia-Herzegovina":   "BIH",
    "Brazil":               "BRA",
    "Canada":               "CAN",
    "Cape Verde":           "CPV",
    "Colombia":             "COL",
    "Congo DR":             "COD",
    "Croatia":              "CRO",
    "Curaçao":              "CUW",
    "Czechia":              "CZE",
    "Côte d'Ivoire":        "CIV",
    "Ecuador":              "ECU",
    "Egypt":                "EGY",
    "England":              "ENG",
    "France":               "FRA",
    "Germany":              "GER",
    "Ghana":                "GHA",
    "Haiti":                "HAI",
    "IR Iran":              "IRN",
    "Iraq":                 "IRQ",
    "Japan":                "JPN",
    "Jordan":               "JOR",
    "Korea Republic":       "KOR",
    "Mexico":               "MEX",
    "Morocco":              "MAR",
    "Netherlands":          "NED",
    "New Zealand":          "NZL",
    "Norway":               "NOR",
    "Panama":               "PAN",
    "Paraguay":             "PAR",
    "Portugal":             "POR",
    "Qatar":                "QAT",
    "Saudi Arabia":         "KSA",
    "Scotland":             "SCO",
    "Senegal":              "SEN",
    "South Africa":         "RSA",
    "Spain":                "ESP",
    "Sweden":               "SWE",
    "Switzerland":          "SUI",
    "Tunisia":              "TUN",
    "Türkiye":              "TUR",
    "United States":        "USA",
    "Uruguay":              "URU",
    "Uzbekistan":           "UZB",
}
